// Runs a research cycle of the Historical Intelligence Engine in a Web Worker (started by the dashboard): reads the
// research dataset (5s candles per pair-hour, the live chart memory, 1M candles), replays it — similar past
// states, walk-forward against baselines, discovered patterns, pair fingerprints — and saves a versioned model.
// The live side (background.js) uses the latest model; nothing here trades. The service worker runs the same
// cycle on its own every few hours (OTC.Research.runCycle).
// It also runs the OTC Randomness & Edge Audit (engine/audit.js) on the same dataset plus the bot's own records,
// and saves the report to the `audits` store.
importScripts('indicators.js', 'engine/core.js', 'engine/stats.js', 'engine/research.js', 'engine/featurelib.js', 'engine/discovery.js',
  'engine/discovery-search.js', 'engine/discovery-assess.js', 'engine/lifecycle.js', 'engine/audit.js', 'db.js');

let stop = false;
const post = (m) => self.postMessage(m);

// the research dataset: 5s candles (collector rows + chart memory, one per time) and 1M candles, per pair
async function dataset() {
  const per5 = {}, per1 = {};
  for (const ch of await DB.all('hist5')) { const m = (per5[ch.asset] ||= new Map()); ch.t.forEach((t, i) => m.set(t, { time: t, open: ch.o[i], high: ch.h[i], low: ch.l[i], close: ch.c[i] })); }
  for (const c of await DB.all('candles_s5')) (per5[c.asset] ||= new Map()).set(c.time, c);
  for (const c of await DB.all('candles_m1')) (per1[c.asset] ||= []).push(c);
  return { per5: Object.fromEntries(Object.entries(per5).map(([a, m]) => [a, [...m.values()]])), per1 };
}

async function runAudit(data) {
  post({ type: 'progress', text: 'التدقيق: تحميل البيانات والسجلات…' });
  // which market: OTC (PO's own prices) or real markets (currencies, crypto, stocks — not generated by PO)
  const market = data.market === 'real' ? 'real' : 'otc', mine = (a) => /_otc$/i.test(a) === (market === 'otc');
  const all = await dataset(), pick = (per) => Object.fromEntries(Object.entries(per).filter(([a]) => mine(a)));
  const per5 = pick(all.per5), per1 = pick(all.per1);
  const opps = market === 'otc' ? (await DB.byIndex('records', 'kind', 'opp')).filter((r) => r.tf === 1) : [];
  const say = (t) => post({ type: 'progress', text: `التدقيق: ${t}` });
  const rep = OTC.Audit.audit({ per5, per1, opps, sigStats: market === 'otc' ? data.sigStats || {} : {} }, { shouldStop: () => stop, onProgress: say });
  if (!rep || stop) { post({ type: 'stopped' }); return; }
  await OTC.Audit.discoveryNulls(rep.engines, { cfg: OTC.config(data.cfg || {}), shouldStop: () => stop, say });
  OTC.Audit.redecide(rep);
  const saved = OTC.Audit.compact(rep);
  saved.market = market;
  saved.id = `audit-${rep.builtAt}`;
  saved.by = data.by || 'dashboard';
  await DB.put('audits', saved);
  const kept = (await DB.all('audits')).sort((a, b) => b.builtAt - a.builtAt);
  for (const m of ['otc', 'real']) for (const old of kept.filter((x) => (x.market || 'otc') === m).slice(3)) await DB.del('audits', old.id); // the last 3 of each market
  post({ type: 'done', kind: 'audit', id: saved.id, verdict: rep.verdict.status, market });
}

self.onmessage = async ({ data }) => {
  if (data.type === 'stop') { stop = true; return; }
  if (data.type === 'audit') { stop = false; try { await runAudit(data); } catch (e) { post({ type: 'error', error: String(e && e.stack || e) }); } return; }
  if (data.type !== 'run') return;
  stop = false;
  try {
    post({ type: 'progress', text: 'تحميل البيانات…' });
    const ds = await dataset(), otc = (per) => Object.fromEntries(Object.entries(per).filter(([a]) => /_otc$/i.test(a))); // the live model: OTC only
    const per5 = otc(ds.per5), per1 = otc(ds.per1);
    let states = null;
    const payout = data.payout || 85;
    const model = OTC.Research.runCycle(per5, per1, {
      payout, shouldStop: () => stop, onProgress: (t) => post({ type: 'progress', text: t }), onStates: (st) => (states = st) });
    if (!model || stop) { post({ type: 'stopped' }); return; }
    model.by = data.by || 'dashboard';
    // Strategy discovery on the same market states: multi-condition rules searched on the oldest 60%, validated with
    // false-discovery control, out-of-sample, walk-forward, robustness — into the one strategy registry (versioned rows).
    model.discovery = {};
    const existing = OTC.Lifecycle.latest(await DB.all('strategies')), previousRuns = await DB.all('discovery_runs');
    for (const tf of [5, 60]) {
      const st = states?.[tf] || [];
      if (stop || st.length < 3000) { model.discovery[tf] = { skipped: `${st.length} states` }; continue; }
      const H = OTC.Research.DEFAULTS.discoverHorizons[tf];
      post({ type: 'progress', text: `${tf === 5 ? '5 ثوانٍ' : 'دقيقة'}: اكتشاف استراتيجيات من حالات السوق…` });
      const ds = OTC.Discovery.datasetFromStates(st, { tf, horizons: H, defaultPayout: payout });
      const cfg = OTC.config({ ...(data.cfg || {}), discovery: { ...(data.cfg?.discovery || {}), expiries: H, timeBudgetSec: 90 } });
      const res = await OTC.Discovery.runCycle(ds, { cfg, tf, defaultPayout: payout, existing, previousRuns, shouldStop: () => stop,
        runId: `RUN-${Date.now()}-S${tf}`, onProgress: (p) => p.stage && post({ type: 'progress', text: `${tf === 5 ? '5 ثوانٍ' : 'دقيقة'}: ${p.stage}${p.dir ? ` ${p.dir}` : ''}` }) });
      if (res.rows.length) await DB.putMany('strategies', res.rows);
      await DB.put('discovery_runs', { ...res.run, report: res.report, source: 'market-states', tf });
      const by = {};
      for (const r of res.rows) by[r.status] = (by[r.status] || 0) + 1;
      model.discovery[tf] = { rows: ds.n, tested: res.rows.length, byStatus: by, runId: res.run.id,
        paperTest: res.rows.filter((r) => r.status === 'PAPER_TEST').map((r) => ({ id: r.strategy_id, name: r.name, dir: r.direction, expiry: r.expiry, oos: r.out_of_sample_results })) };
    }
    await DB.put('research', model);
    const all = (await DB.all('research')).sort((a, b) => b.builtAt - a.builtAt);
    for (const old of all.slice(10)) await DB.del('research', old.id); // keep the last 10 versions
    post({ type: 'done', id: model.id, summary: model.summary });
  } catch (e) {
    post({ type: 'error', error: String(e && e.stack || e) });
  }
};
